theme: hacker

The following Eportfolio contains my final for the Southern New Hampshire Computer Science Program.
The categories that I am going to be graded on are

1. Software Design
2. Algorithnms and Data Structures
3. Databases

I have for this project decided to build one application to tackle all of these graded areas.
